// Code generated by "stringer -type=Type"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Dash-1]
	_ = x[Times-2]
	_ = x[Slash-3]
	_ = x[Power-4]
	_ = x[Remainder-5]
	_ = x[LogicOr-6]
	_ = x[LogicAnd-7]
	_ = x[BitwiseOr-8]
	_ = x[BitwiseAnd-9]
	_ = x[BitwiseXor-10]
	_ = x[Equals-11]
	_ = x[NotEquals-12]
	_ = x[LessThan-13]
	_ = x[LessThanEqual-14]
	_ = x[GreatThan-15]
	_ = x[GreaterThanEqual-16]
	_ = x[TextEquals-17]
	_ = x[TextNotEquals-18]
	_ = x[TextLessThan-19]
	_ = x[TextGreaterThan-20]
	_ = x[OpenCurve-21]
	_ = x[CloseCurve-22]
	_ = x[OpenSquare-23]
	_ = x[CloseSquare-24]
	_ = x[OpenCurly-25]
	_ = x[CloseCurly-26]
	_ = x[Assign-27]
	_ = x[Dot-28]
	_ = x[Comma-29]
	_ = x[Question-30]
	_ = x[Not-31]
	_ = x[Colon-32]
	_ = x[DoubleColon-33]
	_ = x[DoubleDot-34]
	_ = x[RightArrow-35]
	_ = x[Underscore-36]
	_ = x[At-37]
	_ = x[True-38]
	_ = x[False-39]
	_ = x[Text-40]
	_ = x[Number-41]
	_ = x[Name-42]
	_ = x[ColorCode-43]
	_ = x[If-44]
	_ = x[Else-45]
	_ = x[For-46]
	_ = x[Step-47]
	_ = x[In-48]
	_ = x[While-49]
	_ = x[Do-50]
	_ = x[Break-51]
	_ = x[WalkAll-52]
	_ = x[Global-53]
	_ = x[Local-54]
	_ = x[This-55]
	_ = x[Func-56]
	_ = x[When-57]
	_ = x[Any-58]
	_ = x[Undefined-59]
	_ = x[Yield-60]
	_ = x[MatrixPlus-61]
	_ = x[MatrixDash-62]
	_ = x[MatrixTimes-63]
	_ = x[MatrixPower-64]
}

const _Type_name = "PlusDashTimesSlashPowerRemainderLogicOrLogicAndBitwiseOrBitwiseAndBitwiseXorEqualsNotEqualsLessThanLessThanEqualGreatThanGreaterThanEqualTextEqualsTextNotEqualsTextLessThanTextGreaterThanOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyAssignDotCommaQuestionNotColonDoubleColonDoubleDotRightArrowUnderscoreAtTrueFalseTextNumberNameColorCodeIfElseForStepInWhileDoBreakWalkAllGlobalLocalThisFuncWhenAnyUndefinedYieldMatrixPlusMatrixDashMatrixTimesMatrixPower"

var _Type_index = [...]uint16{0, 4, 8, 13, 18, 23, 32, 39, 47, 56, 66, 76, 82, 91, 99, 112, 121, 137, 147, 160, 172, 187, 196, 206, 216, 227, 236, 246, 252, 255, 260, 268, 271, 276, 287, 296, 306, 316, 318, 322, 327, 331, 337, 341, 350, 352, 356, 359, 363, 365, 370, 372, 377, 384, 390, 395, 399, 403, 407, 410, 419, 424, 434, 444, 455, 466}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
